title: Aswendt Lab
#description: Website of the Aswendt Laboratory, Neurology, University Cologne, Germany.
theme: minima

url: "https://aswendtlab.github.io/"
baseurl: "/"
repository: "Aswendt-Lab/aswendtlab.github.io"

show_menu: true
show_footer: true
google_analytics: true

docs_list_title: List of Contents
docs:
  - title: Home
    url: 
  
  - title: Projects
    url: Projects.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Aswendt-Lab"}
    - { platform: youtube, user_url: "https://www.youtube.com/@aswendtlab1639" }

header_pages:
  - news.md
  - projects.md
  - talks.md
  - conferences.md
  - paper.md
  - team.md
  - contact.md
  - imprint.md
  
github:
  is_project_page: false

exclude:
  - gemfiles/
  - Gemfile*
  - README.md
